# Exported from Render on 2026-09-22T01:05:35Z
version: "1"
projects:
- name: weave-wallet
  environments:
  - name: Production
    services:
    - type: web
      name: Weave-1
      runtime: static
      repo: https://github.com/joeswrld/Weave
      staticPublishPath: packages/wallet/dist
      autoDeployTrigger: commit
